addSbtPlugin("org.scala-js"        % "sbt-scalajs"     % "1.15.0")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat"    % "0.5.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"    % "0.10.4")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"     % "0.3.1")
addSbtPlugin("org.wartremover"     % "sbt-wartremover" % "3.4.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"    % "2.5.2")
